apiVersion: v1
kind: Service
metadata:
  name: app-persistente-service
spec:
  selector:
    app: app-persistente
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
