apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-persistente-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: app-storage
  hostPath:
    path: "/mnt/data"
