apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-persistente-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: app-storage
